# wrangler.toml
name = 'hmadmin'
main = "src/index.js"
compatibility_date = "2026-08-30"
compatibility_flags = ["nodejs_compat"]

[assets]
directory = "./public"
binding = "ASSETS"

[[hyperdrive]]
binding = "HYPERDRIVE"
id = "f0fb212752f14f9c948bed3b12dc9c1b"

[vars]
ACTIVATION_CODE_TABLE = "hm_activation_code"
