name = "hmadmin"
main = "src/index.js"

compatibility_date = "2026-08-31"

[assets]
directory = "./public"
binding = "ASSETS"

[[d1_databases]]
binding = "DB"
database_name = "huimeng"
database_id = "3eee9ddf-6d59-4818-a289-0802e7256258"

[vars]
ACTIVATION_CODE_TABLE = "hm_activation_code"
